# Programme Python pour dessiner un avion avec le module turtle

# Programme Python pour dessiner un avion avec le module turtle
# Import du module dessinMSDA
import dessinMSDA as D
# Import du module turtle
D.tur.fillcolor("blue")
D.tur.begin_fill()
D.tur.rt(-45)
D.tur.fd(100)
D.demi_cercle(30)
D.tur.fd(100)
D.tur.rt(60)
D.tur.fd(95)
D.tur.rt(-65)
D.tur.fd(20)
D.tur.rt(-100)
D.tur.fd(80)
D.tur.rt(110)
D.tur.fd(80)
D.tur.rt(65)
D.tur.fd(50)
D.tur.rt(-65)
D.tur.fd(35)
D.tur.rt(-120)
D.tur.fd(60)
D.tur.rt(45)
D.tur.fd(60)
D.tur.rt(-90)
D.tur.fd(30)
D.tur.rt(-90)
D.tur.fd(40)
D.tur.rt(85)
D.tur.fd(80)
D.tur.rt(90)
D.tur.fd(80)
D.tur.rt(-75)
D.tur.fd(21)
D.tur.rt(-87)
D.tur.goto(0, 0)
D.tur.end_fill()

D.turtle.done()